#!/usr/bin/env python3
"""Finite group library for the lift sweep: every group as (name, order,
mult table uint8 o x o, inv array, element orders).  Coverage <= 63:
all abelian; dihedral; dicyclic; metacyclic Z_m x| Z_j (all actions up to
equivalence); specials A4 S4 A5 SL(2,3) Heisenberg27; direct products of
nonabelians with abelians and with each other.  Not complete for exotic
2-groups of order 32/48 (documented limitation).
"""
import numpy as np
from itertools import product as iproduct


class G:
    def __init__(self, name, elems, mulf):
        self.name = name
        self.order = len(elems)
        idx = {e: i for i, e in enumerate(elems)}
        self.mul = np.zeros((self.order, self.order), dtype=np.uint8)
        for i, a in enumerate(elems):
            for j, b in enumerate(elems):
                self.mul[i, j] = idx[mulf(a, b)]
        # identity: e with e*x = x for all x
        ids = [i for i in range(self.order)
               if all(self.mul[i, j] == j for j in range(self.order))]
        assert len(ids) == 1, name
        self.id = ids[0]
        self.inv = np.zeros(self.order, dtype=np.uint8)
        for i in range(self.order):
            js = np.where(self.mul[i] == self.id)[0]
            assert len(js) == 1, name
            self.inv[i] = js[0]
        # element orders
        self.eord = np.zeros(self.order, dtype=np.int32)
        for i in range(self.order):
            x, k = i, 1
            while x != self.id:
                x = int(self.mul[x, i])
                k += 1
            self.eord[i] = k
        self.involutions = [i for i in range(self.order) if self.eord[i] == 2]
        self.abelian = bool((self.mul == self.mul.T).all())

    def validate(self):
        o = self.order
        m = self.mul
        # associativity (full check; o<=63 so o^3 <= 250k)
        a = m[m, :][:, :, :]     # a[i,j,k] = (i*j)*k
        b = m[:, m]              # b[i,j,k] = i*(j*k)
        assert (a == b).all(), f"assoc fail {self.name}"
        # latin square
        for i in range(o):
            assert len(set(m[i])) == o and len(set(m[:, i])) == o, self.name
        return True


def cyclic_els(m):
    return list(range(m)), lambda a, b: (a + b) % m


def abelian_group(factors):
    els = list(iproduct(*[range(f) for f in factors]))
    def mul(a, b):
        return tuple((x + y) % f for x, y, f in zip(a, b, factors))
    return G("Z" + "xZ".join(map(str, factors)), els, mul)


def dihedral(m):
    els = [(r, s) for s in range(2) for r in range(m)]
    def mul(x, y):
        r1, s1 = x; r2, s2 = y
        return ((r1 + (r2 if s1 == 0 else -r2)) % m, (s1 + s2) % 2)
    return G(f"D{m}", els, mul)


def dicyclic(m):
    """Dic_m, order 4m: <a,b | a^{2m}=1, b^2=a^m, bab^-1=a^-1>."""
    els = [(r, s) for s in range(2) for r in range(2 * m)]
    def mul(x, y):
        r1, s1 = x; r2, s2 = y
        if s1 == 0:
            r, s = (r1 + r2) % (2 * m), s2
        else:
            r, s = (r1 - r2) % (2 * m), (s1 + s2) % 2
            if s1 == 1 and s2 == 1:
                r = (r + m) % (2 * m)
        return (r, s % 2)
    return G(f"Dic{m}", els, mul)


def metacyclic(m, j, u):
    """Z_m x|_u Z_j with u^j = 1 mod m: (a,s)(b,t) = (a + u^s b mod m, s+t mod j)."""
    els = [(a, s) for s in range(j) for a in range(m)]
    pw = [pow(u, s, m) for s in range(j)]
    def mul(x, y):
        a, s = x; b, t = y
        return ((a + pw[s] * b) % m, (s + t) % j)
    return G(f"Z{m}:Z{j}u{u}", els, mul)


def perm_group(name, gens, deg):
    """Group generated by permutation tuples."""
    idp = tuple(range(deg))
    els = {idp}
    frontier = [idp]
    while frontier:
        new = []
        for p in frontier:
            for g in gens:
                q = tuple(p[g[i]] for i in range(deg))
                if q not in els:
                    els.add(q)
                    new.append(q)
        frontier = new
    def mul(p, q):
        return tuple(p[q[i]] for i in range(deg))
    return G(name, sorted(els), mul)


def direct(g1, g2):
    els = [(a, b) for a in range(g1.order) for b in range(g2.order)]
    def mul(x, y):
        return (int(g1.mul[x[0], y[0]]), int(g2.mul[x[1], y[1]]))
    out = G(f"{g1.name}x{g2.name}", els, mul)
    return out


def build_library(max_order=63):
    lib = []
    # all abelian groups: per order, all multisets of prime-power factors
    def partitions(n):
        if n == 0:
            yield []
            return
        for k in range(n, 0, -1):
            for rest in partitions(n - k):
                if not rest or k >= rest[0]:
                    yield [k] + rest
    from sympy import factorint  # not available; do manual
    raise SystemExit("use build_library2")


def factorize(n):
    f = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            f[d] = f.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def partitions(n):
    if n == 0:
        yield []
        return
    for k in range(n, 0, -1):
        for rest in partitions(n - k):
            if not rest or k >= rest[0]:
                yield [k] + rest


def build_library2(max_order=63, verbose=False):
    lib = []
    seen_names = set()
    def add(g):
        if g.order <= max_order and g.name not in seen_names:
            seen_names.add(g.name)
            lib.append(g)
    # abelian
    for order in range(2, max_order + 1):
        fac = factorize(order)
        percomp = []
        for p, e in fac.items():
            percomp.append([[p ** x for x in part] for part in partitions(e)])
        for combo in iproduct(*percomp):
            factors = sorted([f for comp in combo for f in comp])
            add(abelian_group(factors))
    # dihedral / dicyclic
    for m in range(3, max_order // 2 + 1):
        add(dihedral(m))
    for m in range(2, max_order // 4 + 1):
        add(dicyclic(m))
    # metacyclic with distinct actions (dedupe u ~ u^k, gcd(k,j)=1)
    for m in range(3, max_order // 2 + 1):
        for j in range(2, max_order // m + 1):
            us = [u for u in range(2, m) if pow(u, j, m) == 1
                  and all(pow(u, d, m) != 1 for d in range(1, j) if j % d == 0)]
            done = set()
            for u in us:
                if u in done:
                    continue
                orbit = {pow(u, k, m) for k in range(1, j) if
                         np.gcd(k, j) == 1} | {u}
                done |= orbit
                add(metacyclic(m, j, u))
    # specials via permutation generators
    add(perm_group("A4", [(1, 2, 0, 3), (0, 2, 3, 1)], 4))
    add(perm_group("S4", [(1, 0, 2, 3), (1, 2, 3, 0)], 4))
    add(perm_group("A5", [(1, 2, 0, 3, 4), (0, 1, 3, 4, 2)], 5))
    # SL(2,3): order 24, as permutations of the 8 nonzero vectors of F3^2
    vecs = [(a, b) for a in range(3) for b in range(3) if (a, b) != (0, 0)]
    vi = {v: i for i, v in enumerate(vecs)}
    def matperm(M):
        return tuple(vi[((M[0][0] * v[0] + M[0][1] * v[1]) % 3,
                         (M[1][0] * v[0] + M[1][1] * v[1]) % 3)] for v in vecs)
    add(perm_group("SL23", [matperm(((1, 1), (0, 1))), matperm(((0, 2), (1, 0)))], 8))
    # Heisenberg mod 3 = UT(3,3), order 27, exponent 3
    els27 = list(iproduct(range(3), repeat=3))
    def hmul(x, y):
        a, b, c = x; d, e, f = y
        return ((a + d) % 3, (b + e) % 3, (c + f + a * e) % 3)
    add(G("Heis3", els27, hmul))
    # direct products nonabelian x (abelian or nonabelian)
    core = [g for g in lib if not g.abelian]
    small_ab = [g for g in lib if g.abelian and g.order <= 31]
    prods = []
    for g1 in core:
        for g2 in small_ab + core:
            if g1.order * g2.order <= max_order:
                if g2.abelian or g1.name <= g2.name:
                    prods.append(direct(g1, g2))
    for p in prods:
        add(p)
    return lib


if __name__ == "__main__":
    lib = build_library2(63)
    for g in lib:
        g.validate()
    byorder = {}
    for g in lib:
        byorder.setdefault(g.order, []).append(g.name)
    tot = 0
    for o in sorted(byorder):
        tot += len(byorder[o])
        print(f"order {o:3d}: {len(byorder[o]):3d}  {', '.join(byorder[o][:8])}"
              + (" ..." if len(byorder[o]) > 8 else ""))
    print(f"TOTAL {tot} groups, all validated (assoc+latin)")
